- .gitignore
- package-lock.json
- package.json
- src/BlacklistManager.ts
- src/RemoteDataManager.ts
- src/TrustedSourceManager.ts
- src/universalis.ts
- test/BlacklistManagerTest.ts
- test/MongoFixture.ts
- test/RemoteDataManagerTest.ts
- test/TrustedSourceManagerTest.ts
- tslint.json
- added `ts-node` dependency to support writing tests in TypeScript
- modified `BlacklistManager`, created `TrustedSourceManager` as examples of async Mongo-based stores with proper index initialization
- added type information to `RemoteDataManager`, fixed BOM handling
- allowed variable names starting with `_` in `tslint` config
> Tests in TypeScript, Mongo indices, few fixes and improvements

- src/universalis.ts
Hello,
This fix ignores the worlds that aren't flagged as public in the World.csv file.
This solves an issue causing the worldMap entries to be overwritten with a wrong ID for the 3 worlds Chocobo, Moogle, and Namazu.
Example:
[https://universalis.app/api/Moogle/27750](https://universalis.app/api/Moogle/27750) at this link, you can see that Moogle is resolved as worldID 166, where it should've been resolved as worldID 71.
[https://universalis.app/api/71/27750](https://universalis.app/api/71/27750) works properly and returns the actual results from Moogle.
> Fix dupes in World.csv causing wrong ID mapping

- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
No clue why an element was getting removed from minimizedSales every iteration, but I believe that to be the culprit.
'i' increases with every iteration of the loop, but the element at the 0th index is also getting removed every iteration.  so we're esentially double-iterating, skipping every other entry.
> Maybe fixed history merge

- src/Universalis.Application.Tests/Caching/MemoryCacheTests.cs
- src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
- src/Universalis.Application.Tests/Controllers/V1/DeleteListingControllerTests.cs
- src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
- src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
- src/Universalis.Application/Caching/CachedCurrentlyShownData.cs
- src/Universalis.Application/Caching/CachedCurrentlyShownQuery.cs
- src/Universalis.Application/Caching/CurrentlyShownCache.cs
- src/Universalis.Application/Caching/ICopyable.cs
- src/Universalis.Application/Caching/MemoryCache.cs
- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V1/DeleteListingController.cs
- src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs
- src/Universalis.Application/Startup.cs
- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
- src/Universalis.Application/Views/V1/ListingView.cs
- src/Universalis.Application/Views/V1/SaleView.cs
This changes the cache to use MemberwiseClone to copy objects, rather than using JSON serialization to ensure a generalizable deep copy. This removes a significant amount of string object creation and unnecessary parsing, at the cost of requiring types to have their own clone implementations.
> Remove de/serialization methods from cache

- src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
- src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
- src/Universalis.Application/Common/InputProcessing.cs
- src/Universalis.Application/Common/PartiallySerializable.cs
- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/PartiallySerializableJsonConverter.cs
- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs
- src/Universalis.Application/Startup.cs
- src/Universalis.Application/Views/V1/CurrentlyShownMultiView.cs
- src/Universalis.Application/Views/V1/CurrentlyShownView.cs
- src/Universalis.Application/Views/V1/ListingView.cs
- src/Universalis.Application/Views/V1/SaleView.cs
- src/Universalis.Application/Views/V2/CurrentlyShownMultiViewV2.cs
A lot of community projects, especially plugins, utilize the Universalis market board current data API to retrieve item prices.
With the addition of regional requests the amount of data transferred per item requested can reach significant volumes and especially for plugins, the developers cannot guarantee the internet connection of their users will be able to handle the downloads.
As the developer of Price Insight which tries to streamline the process of checking prices for the user as much as possible, using caching and prefetching, I'd like to keep the load to the Universalis server as minimal as possible too.
Requesting https://universalis.app/api/v2/North-America/37840,37843,38263,38268 currently requires ~2MB.
With this PR it will be possible to select the fields required, for …
> Add a field filter query parameter to the market board current data API

- src/Universalis.Application/Controllers/PartiallySerializableJsonConverter.cs
This change computes the properties and attributes of partially-serializable types once, during static initialization, rather than every read/write call. This should be replaced with code generation in .NET 7.
> Static-initialize reflected properties

- deployment/docker-compose.yml
- devenv/docker-compose.yml
- src/Universalis.Application/Universalis.Application.csproj
- src/Universalis.Application/appsettings.Development.json
- src/Universalis.Application/appsettings.Production.json
- src/Universalis.DbAccess/DbAccessExtensions.cs
- src/Universalis.DbAccess/MarketBoard/TaxRatesStore.cs
- src/Universalis.DbAccess/Universalis.DbAccess.csproj
This uses Memcached to set up a distributed cache for tax rate data. Memcached is not ideal for this, but Making Redis work will require a moderate refactor, since I'm already using a Redis client for my primary store. Microsoft DI does not support providing multiple services on a single interface type.
> Add distributed cache for tax rates

- src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
- src/Universalis.DbAccess/MarketBoard/TaxRatesStore.cs
These clones return an interface type instead of their own type, so they get serialized as empty objects. They're also unnecessary here.
> Remove unnecessary and error-prone clones

- src/Universalis.Application.Tests/Controllers/V1/Extra/Stats/RecentlyUpdatedItemsControllerTests.cs
- src/Universalis.Application/Controllers/V1/Extra/Stats/LeastRecentlyUpdatedItemsController.cs
- src/Universalis.Application/Controllers/V1/Extra/Stats/MostRecentlyUpdatedItemsController.cs
- src/Universalis.Application/Controllers/V1/Extra/Stats/RecentlyUpdatedItemsController.cs
This changes the recently-updated stats endpoints so that they do not show data for items that are not marketable.
> Don't show stats for unmarketable items

- src/Universalis.Application.Tests/Controllers/V1/DeleteListingControllerTests.cs
- src/Universalis.Application.Tests/Controllers/V1/Extra/Stats/SourceUploadCountsControllerTests.cs
- src/Universalis.Application.Tests/Controllers/V1/UploadControllerTests.cs
- src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
- src/Universalis.Application.Tests/Uploads/Behaviors/PlayerContentUploadBehaviorTests.cs
- src/Universalis.Application.Tests/Uploads/Behaviors/SourceIncrementUploadBehaviorTests.cs
- src/Universalis.Application.Tests/Uploads/Behaviors/TaxRatesUploadBehaviorTests.cs
- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V1/DeleteListingController.cs
- src/Universalis.Application/Controllers/V1/UploadController.cs
- src/Universalis.Application/Startup.cs
- src/Universalis.Application/TrustedSourceHashCache.cs
- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
- src/Universalis.Application/Uploads/Behaviors/PlayerContentUploadBehavior.cs
- src/Universalis.Application/Util.cs
- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownStoreTests.cs
- src/Universalis.DbAccess/AccessControl/TrustedSourceUploadCountStore.cs
- src/Universalis.DbAccess/DbAccessExtensions.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
- src/Universalis.DbAccess/MarketBoard/SaleStore.cs
- src/Universalis.Entities/AccessControl/ApiKey.cs
The type of hashing that is done for IDs is extremely small and using Task results causing unnecessary allocations. If you want to parallelize it, it would be better to do ValueTask; however, we are not waiting on IO as we are getting back the results fairly quickly.
For Redis, I've removed the ToDictionary/HGETALL and swapped it for HMGET and specify the fields we want. This returns back the values in the same order we requested them and allows us to avoid those allocations. Additionally, we can remove the utility functions since the nullability of primitive types is the default value.
I've kicked the tires on my local testing setup, but I would like a review from production-y data.
> Improve Redis and Hash performance

- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
Usually, invalid IDs should result in no data being found, but for some reason using 0 causes production to throw an exception. This change returns early if an invalid item ID is provided.
> Fix weird error when IDs are invalid

- devenv/.gitignore
- devenv/docker-compose.yml
- src/Universalis.Application.Tests/SchemaSeedDataGenerator.cs
- src/Universalis.Application/Controllers/V3/Market/OverviewController.cs
- src/Universalis.Application/Program.cs
- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
- src/Universalis.Application/Util.cs
- src/Universalis.Application/appsettings.Development.json
- src/Universalis.DbAccess.Tests/DbFixture.cs
- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/SaleStoreTests.cs
- src/Universalis.DbAccess.Tests/SeedDataGenerator.cs
- src/Universalis.DbAccess/DbAccessExtensions.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
- src/Universalis.DbAccess/MarketBoard/IListingStore.cs
- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
- src/Universalis.DbAccess/Migrations/0001_CreateMarketItemTable.cs
- src/Universalis.DbAccess/Migrations/0002_CreateSaleTable.cs
- src/Universalis.DbAccess/Migrations/0003_CreateApiKeyTable.cs
- src/Universalis.DbAccess/Migrations/0004_AddApiKeyName.cs
- src/Universalis.DbAccess/Migrations/0005_MakeColumnsNullable.cs
- src/Universalis.DbAccess/Migrations/0006_CreateCharacterTable.cs
- src/Universalis.DbAccess/Migrations/0007_CreateFlaggedUploaderTable.cs
- src/Universalis.DbAccess/Migrations/0008_AddMannequinToSales.cs
- src/Universalis.DbAccess/Migrations/0009_CreateListingTable.cs
- src/Universalis.DbAccess/Queries/MarketBoard/ListingQuery.cs
- src/Universalis.DbAccess/Universalis.DbAccess.csproj
- src/Universalis.Entities/Character.cs
- src/Universalis.Entities/MarketBoard/Listing.cs
As listings are requested from Redis, they'll be added to Postgres if they aren't already there. New uploads will go straight to Postgres. Redis is still used for last upload times and upload applications, for now.
Old listings are not deleted, just hidden. I still need to experiment to see if deleting old listings immediately is performant, or if a cronjob is needed.
> Gradually add listings to Postgres

- Dockerfile
Upgrading to Npgsql.Json.NET 7 requires System.Text.JSON 7 at runtime.
> Use .NET 7 runtime in container

- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
This breaks data migration, since many listing IDs are currently empty. The listing ID is the primary key for a listing entity.
> Implement workaround for empty listing IDs

- src/Universalis.Application.Tests/Mocks/DbAccess/MarketBoard/MockCurrentlyShownDbAccess.cs
- src/Universalis.Application.Tests/Mocks/DbAccess/MarketBoard/MockHistoryDbAccess.cs
- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/HistoryControllerBase.cs
- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownDbAccessTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/MarketItemStoreTests.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownDbAccess.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
- src/Universalis.DbAccess/MarketBoard/HistoryDbAccess.cs
- src/Universalis.DbAccess/MarketBoard/ICurrentlyShownDbAccess.cs
- src/Universalis.DbAccess/MarketBoard/ICurrentlyShownStore.cs
- src/Universalis.DbAccess/MarketBoard/IListingStore.cs
- src/Universalis.DbAccess/MarketBoard/IMarketItemStore.cs
- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
- src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
- src/Universalis.DbAccess/Queries/MarketBoard/CurrentlyShownManyQuery.cs
- src/Universalis.DbAccess/Queries/MarketBoard/ListingManyQuery.cs
- src/Universalis.DbAccess/Queries/MarketBoard/MarketItemManyQuery.cs
- src/Universalis.DbAccess/Queries/MarketBoard/MarketItemQuery.cs
- src/Universalis.DbAccess/WorldItemPair.cs
I didn't update SaleStore because it doesn't seem to be suffering from delays right now; that can be adjusted if needed later on.
> Update database layer to support batching across worlds and items

- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
- src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
Uses `CommandBehavior.SequentialAccess` where possible, and uses `ExecuteScalarAsync` in `MarketItemStore.Retrieve`.
> Tune Npgsql command options

- src/Universalis.GameData/CsvGameDataProvider.cs
- src/Universalis.GameData/DynamicGameDataProvider.cs
This loads the CSV game data provider first, and loads Lumina in the background to use it once it's ready. CSV provider requests have been deduplicated.
> Optimize game data loading

- src/Universalis.DbAccess.Tests/AccessControl/ApiKeyStoreTests.cs
- src/Universalis.DbAccess.Tests/CharacterStoreTests.cs
- src/Universalis.DbAccess.Tests/DatabaseCollection.cs
- src/Universalis.DbAccess.Tests/DbFixture.cs
- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/MarketItemStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/SaleStoreTests.cs
- src/Universalis.DbAccess.Tests/SeedDataGenerator.cs
- src/Universalis.DbAccess.Tests/Uploads/DailyUploadCountStoreTests.cs
- src/Universalis.DbAccess.Tests/Uploads/FlaggedUploaderStoreTests.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
- src/Universalis.DbAccess/MarketBoard/IListingStore.cs
- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
- src/Universalis.GameData.Tests/GameDataProviderTests.cs
MVCC allows us to have a transaction view concurrently modified for both
views (grabbing the stall content and inserting the fresh content). This
should prevent any issues with needing a post cleanup job; however, this
will cause use to have VACUUM and page fragmentation, so we should test
this more.
> update: modify listings from upsert model to replace model.

- src/Universalis.DbAccess.Tests/Uploads/MostRecentlyUpdatedDbAccessTests.cs
- src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
- src/Universalis.DbAccess/Uploads/IWorldItemUploadStore.cs
- src/Universalis.DbAccess/Uploads/WorldItemUploadStore.cs
This allows the entire Listings database in Redis to be decommissioned, freeing up the node for PostgreSQL.
> Take listing upload states from the WorldItemUpload sorted set

- src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
This should fix the function only returning as many worlds as there are items specified
> Fix MarketItemStore RequestMany batching

- src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
It might be possible for a split sales/listings upload pair to cause listings to become inconsistent. If listings go through first, and then sales go through, the sales upload can pull old data and reinsert it after the listings upload completes.
This is convoluted behavior.
> Fix split uploads possibly breaking listings

- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
I introduced a bug causing incorrect sales to be sent along which needs to be merged before re-enabling this.
> Temporarily block Dalamud from uploading sales

- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V1/HistoryController.cs
- src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V2/HistoryController.cs
Added clarification to fields where it says it sets the number of entries/listings to return when multiple IDs can be queried, mean they're a limit per item ID specified and not per query.
e.g. from [Market Board Current Data ](https://docs.universalis.app/#market-board-current-data) :
**entries**
_string (query)_ `The number of recent history entries to return. By default, a maximum of 5 entries will be returned.`
Becomes:
**entries**
_string (query)_ `The number of recent history entries to return per item. By default, a maximum of 5 entries will be returned.`
Actually caused me confusion the first time I read it and forgot to do something about it until now...
Better late than never I guess😅 
I'm not familiar with C# XML documentation comments but I believe this is the way to update …
> Doc clarification on entries-to-return/listings-to-return parameters when multiple itemIDs may be queried at once

- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/HistoryControllerBase.cs
- src/Universalis.DataTransformations.Tests/StatisticsTests.cs
- src/Universalis.DataTransformations/Statistics.fs
Velocity currently only shows the amount of sales per day but doesn't include the amount of items sold in total.
I believe this should be included either in `saleVelocity`, or if non-breaking as a new attribute.
> Factor in quantity of items sold for velocity calculation

- src/Universalis.GameData/DynamicGameDataProvider.cs
Currently, the server loads CSVs first for a fast initialization, followed by swapping to Lumina once it's loaded. However, if the CSVs fail to load for some reason (due to an update in this case, but it's unclear how this broke things in Universalis) the application will simply fail to handle any requests. This change errs towards using Lumina, and falling back to CSVs if Lumina fails, which is more reliable at the cost of being slower on the server.
> Load Lumina first and fall back to CSVs

- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
Should fix issues where listings or sales seemingly randomly don't show up on the website after an upload.
> Accept uploads when sales/listings are combined and one array is empty

- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs
This just wires the existing entries parameter into the query to allow more than 20 entries to be returned.
> Allow the maximum number of entries in the currently-shown endpoint to be more than 20

- src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
- src/Universalis.Application.Tests/UtilTests.cs
- src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
- src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
- src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs
- src/Universalis.Application/Util.cs
- src/Universalis.Application/Views/V1/ListingView.cs
This PR fixes how GST is calculated and makes it not precalculated in the unit/total prices of listing objects by default. Previously, the API calculated the GST of a listing's total price as `ceil(pq * 1.05)`, where `p` is the unit price and `q` is the quantity of the item. For GST of the unit price, the calculation done was `ceil(p * 1.05)`. Test cases have been added for tax calculation.
How the API should compute unit GST is open to interpretation, as the game itself never does this - it only computes GST over the total price.
Either way, the API's behavior was incorrect for two reasons:
1. If the API does compute GST for unit prices, it should do so by dividing the total tax by the quantity of the item sold, and returning the result as an exact (non-rounded) value. I did not want to …
> Fix GST calculation and make GST a separate property of listings instead of adding it to the unit and total prices

- src/Universalis.DbAccess/DbAccessExtensions.cs
By default, query idempotence for custom statements is set to false, so speculative execution is never used. Here, we never use non-idempotent CQL statements (as defined by the docs), so we can default to true for this setting.
https://docs.datastax.com/en/developer/csharp-driver/3.20/features/speculative-retries/#query-idempotence
> Declare query idempotence in DataStax driver by default

- src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
Currently, when querying for multiple world/item listings at once, we instantiate a batch command and add each world/item pair as N queries within that. However, we can instead do a single query for all worlds/items and rebuild the same result in a dictionary. This change does that.
> Perform multi-item listing retrievals in a single query

- src/Universalis.DbAccess/Universalis.DbAccess.csproj
Method not found: 'System.Type[] Npgsql.Internal.PgSerializerOptions.get_WellKnownTextTypes()'.
> Downgrade Npgsql back to 8.0.2 due to a new method not found exception

- src/Universalis.DbAccess/MarketBoard/ListingStore.cs
No longer using a batch command, so this is no longer required - requests often time out on it anyways.
> Remove connection acquisition from ListingStore.RetrieveManyLive

- src/Universalis.DbAccess.Tests/MarketBoard/CurrentlyShownStoreTests.cs
- src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
- src/Universalis.DbAccess/MarketBoard/HistoryDbAccess.cs
This PR is part of the optimization effort to reduce the load on the Universalis API.
This is a simple change to completely skip accessing the `sales` DB when `entries` query parameter is set to 0, which would otherwise result in a query that returns 0 rows (see [LIMIT usage](https://github.com/Universalis-FFXIV/Universalis/blob/908189276693f608e2837c2740ec67c4a699507a/src/Universalis.DbAccess/MarketBoard/SaleStore.cs#L178)).
In addition, this PR updates the tests in `Universalis.DbAccess.Tests.MarketBoard.CurrentlyShownStoreTests` to reflect recent changes, including the removal of the seller/creator CIDs (#1345).
> Skip sales DB call when entries==0 for currently shown API call (#1318)

- src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
- src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
- src/Universalis.Application/Uploads/Schema/Listing.cs
Fixes an issue where some listings have a `lastReviewTime` of 0 in the API.
> Reject uploads with invalid LastReviewTime

- src/Universalis.DbAccess.Tests/Uploads/MostRecentlyUpdatedDbAccessTests.cs
- src/Universalis.DbAccess/Uploads/MostRecentlyUpdatedDbAccess.cs
Should fix the least-recently-updated endpoint showing incorrect results on data centers vs. single worlds.
> Compare timestamps correctly and without overflows
