Universalis-FFXIV/Universalis

README.md
examples/DiscordMarketCommand.js
package.json
src/ExtraDataManager.ts
src/TrustedSourceManager.ts
src/cli/commands/addkey.ts
src/cli/commands/drop.ts
src/cli/commands/dropex.ts
src/cli/commands/rmkey.ts
src/cli/commands/upstats.ts
src/cli/unic.ts
src/models/CLIResources.ts
src/models/RecentlyUpdated.ts
src/models/WorldItemPair.ts
src/trackers/HistoryTracker.ts
src/trackers/PriceTracker.ts
src/universalis.ts
src/validate.ts
unic.bat
unic.sh

CLI Features
- `addkey`
- `rmkey`
- `upstats`
- `drop`
- `dropex`
Updated endpoint /extra/stats/least-recently-updated
- Now has world/DC query parameter
Formatting
- Classes are now factories so that they don't have `async` arrow functions that aren't `await`ed built into their constructors

CLI Updates, formatting changes, and /least-recently-updated

---

.eslintrc.json
README.md
src/ExtraDataManager.ts
src/RemoteDataManager.ts
src/cli/unic.ts
src/trackers/HistoryTracker.ts
src/universalis.ts
tsconfig.json
unic.sh

The data is requested from XIVAPI asynchronously, and the containing array is usable while it is being populated.

Nonrandom algorithm for least-recently-updated

---

package.json
src/BlacklistManager.ts
src/ContentIDCollection.ts
src/ExtraDataManager.ts
src/universalis.ts
test/RemoteDataManagerTest.ts
test/test.js

Fix missing case in least-recently-updated

---

README.md
src/cli/commands/logs.ts
src/cli/unic.ts
src/db/ExtraDataManager.ts
src/endpoints/parseTaxRates.ts
src/endpoints/upload.ts
src/universalis.ts

I should really use an actually useful commit/PR naming format like Teamcraft or something. Soon^TM

Tax rate fixes n' stuff

---

src/endpoints/parseListings.ts

This should never happen, but in the event that it does, things won't break.

Add an output handler for the input validation being skipped.

---

src/endpoints/parseListings.ts

This way I can work on live data without disrupting service

debug: add debug flag to listings endpoint

---

src/validate.ts

messy implementation, but it'll be easy to clean later

whoops, include chinese world IDs in validation

---

package-lock.json
package.json
src/initializeWorldMappings.ts
src/universalis.ts
src/util.ts
src/validate.ts
test/BlacklistManagerTest.ts
test/RemoteDataManagerTest.ts
test/initializeWorldMappingsTest.ts
test/validateTest.ts

...also fixed an issue in which romanized Chinese worlds weren't being added to the world maps. It's unrelated to the 422s but still important to fix.

better tests, file-logged listing failures and console beeps

---

src/db/ExtraDataManager.ts

using the filter method mixed in data from outside the query range, for some reason

build the marketable filter into the query itself

---

src/endpoints/parseListings.ts

Don't show listings with a quantity of 0

---

devenv/websocket-client/index.js
src/Universalis.Application/Realtime/SocketClient.cs

The JSON parser was throwing an exception upon encountering 0x00.

Fix client message decoding

---

.gitignore
devenv/websocket-client/index.js
devenv/websocket-client/package-lock.json
devenv/websocket-client/package.json
src/Universalis.Application.Tests/Mocks/Realtime/Messages/MockMessage.cs
src/Universalis.Application.Tests/Universalis.Application.Tests.csproj
src/Universalis.Application/Realtime/Messages/EventCondition.cs
src/Universalis.Application/Realtime/Messages/ItemUpdate.cs
src/Universalis.Application/Realtime/Messages/ListingsAdd.cs
src/Universalis.Application/Realtime/Messages/ListingsRemove.cs
src/Universalis.Application/Realtime/Messages/SalesAdd.cs
src/Universalis.Application/Realtime/Messages/SocketMessage.cs
src/Universalis.Application/Realtime/SocketClient.cs
src/Universalis.Application/Universalis.Application.csproj
src/Universalis.sln

Use BSON serialization in WebSocket messages

---

src/Universalis.Application.Tests/Mocks/GameData/MockGameDataProvider.cs
src/Universalis.Application.Tests/SchemaSeedDataGenerator.cs
src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
src/Universalis.DbAccess.Tests/SeedDataGenerator.cs
src/Universalis.GameData/CsvGameDataProvider.cs
src/Universalis.GameData/IGameDataProvider.cs
src/Universalis.GameData/LuminaGameDataProvider.cs
src/Universalis.GameData/RobustGameDataProvider.cs

Validate market item stack sizes

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

Waiting until getting a confirmation on new uploads clearing these out; if that isn't the case then I have a bigger problem.

Filter out listings with no price/quantity

---

src/Universalis.Application/Caching/MemoryCache.cs

Assuming data is accessed randomly or in order, an MRU cache will have more cache hits than an LRU. We shall see if that is true here.

Experiment with MRU cache

---

src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
src/Universalis.DbAccess/MarketBoard/IMarketItemStore.cs
src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
src/Universalis.Entities/MarketBoard/MarketItem.cs

This reverts commit b38920cf5e2e02e78a0161aa46dced87a19b6692.

Revert "Cache update times"

---

src/Universalis.Application.Tests/Mocks/DbAccess/Uploads/MockRecentlyUpdatedItemsDbAccess.cs
src/Universalis.DbAccess/Uploads/IRecentlyUpdatedItemsDbAccess.cs
src/Universalis.DbAccess/Uploads/RecentlyUpdatedItemsDbAccess.cs

This reverts commit 5a37c75c843e0f40c8bd5f40d067f32f2d0783c4.

Revert "Fix recently updated items cache (#837)"

---

src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
src/Universalis.DbAccess/MarketBoard/IMarketItemStore.cs
src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
src/Universalis.Entities/MarketBoard/MarketItem.cs

This reverts commit 235c2e1b1e045169a88a311caf6ce935a86a6481.

Revert "Revert "Cache update times""

---

src/Universalis.Application/Caching/CurrentlyShownCache.cs
src/Universalis.DbAccess/MarketBoard/MarketItemStore.cs
src/Universalis.DbAccess/MarketBoard/TaxRatesDbAccess.cs
src/Universalis.DbAccess/Uploads/RecentlyUpdatedItemsDbAccess.cs
src/Universalis.DbAccess/Uploads/WorldUploadCountDbAccess.cs

Caching needs to be distributed, so application-level caching needs to be removed.

Remove application-level caching

---

src/Universalis.Application.Tests/Controllers/V1/DeleteListingControllerTests.cs
src/Universalis.Application.Tests/LogEvent.cs
src/Universalis.Application.Tests/LogFixture.cs
src/Universalis.Application/Controllers/V1/DeleteListingController.cs

Adds WS support to the DeleteListing controller.

Add single listing deletions to WebSocket events

---

src/Universalis.Application.Tests/Controllers/V1/Extra/Stats/RecentlyUpdatedItemsControllerTests.cs
src/Universalis.Application.Tests/Controllers/V1/Extra/Stats/TradeVolumeControllerTests.cs
src/Universalis.Application.Tests/Mocks/DbAccess/MarketBoard/MockSaleStatisticsDbAccess.cs
src/Universalis.Application/Controllers/V1/Extra/Stats/TradeVolumeController.cs
src/Universalis.Application/Views/V1/Extra/Stats/UnitTradeVolumeView.cs
src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
src/Universalis.DbAccess/MarketBoard/ISaleStatisticsDbAccess.cs
src/Universalis.DbAccess/MarketBoard/ISaleStore.cs
src/Universalis.DbAccess/MarketBoard/SaleStatisticsDbAccess.cs
src/Universalis.DbAccess/MarketBoard/SaleStore.cs
src/Universalis.DbAccess/Queries/MarketBoard/UnitTradeVolumeQuery.cs

Adds Gil trade volume information to the existing unstable trade volume endpoint.

Add Gil trade volume to the API

---

src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs

Bring back the listings cache again

---

src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

This reverts commit 240cbb2c0a2f96616b208def1679359aaec89d39.

Revert "Revert linking sales back into current data"

---

src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

This reverts commit f2ac071f5557360b39edca46a491d3946897840f.

Revert "Revert "Revert linking sales back into current data" (#1010)"

---

src/Universalis.DbAccess/MarketBoard/SaleStore.cs

Using FetchPageAsync is only recommended if you are going to use a paging token system. Just allow the DataStax driver to paginate using the default paging size. This reduced the amount of object allocations and CPU usage. Additionally, the latency time is faster on my test machine that checking the cache is now the bottleneck.
Additionally, return IEnumberable directly to allow the caller to be able to use it more efficiently.
The explicit ORDER BY is to show how we want the data, the table is already sorted by the sale_time.

perf(MarketBoard): sort and limit in CQL and use automatic paging

---

src/Universalis.DbAccess/MarketBoard/ListingStore.cs

The listing ID doesn't need to be returned from the query because it's already available in the listing object itself. Furthermore, these can all be executed as a single batch, with an implicit transaction.

Make listing inserts not stupid

---

src/Universalis.DbAccess/MarketBoard/ListingStore.cs

I think this functionality is fine; refer to the comment for more info.

Handle repeated uploads of the same listing

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs

This may also help with vCPU usage.
First commit reduced memory allocations and the rest optimize the flow of data to be more properly asynchronous.

CurrentlyShown optimizations

---

src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs

This is probably the third time I've reverted this type of change.

Don't cache currently shown data at all

---

src/Universalis.Application/Program.cs
src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs

Freeze changes and disable PostgreSQL calls

---

src/Universalis.Application/Program.cs
src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs

This change should not be deployed to production as-is, due to lock contention that occurs when reading and writing listing batches.

Enable PostgreSQL again

---

build/_build.csproj
src/Universalis.Alerts.Tests/Universalis.Alerts.Tests.csproj
src/Universalis.Alerts/Universalis.Alerts.csproj
src/Universalis.Application.Tests/Universalis.Application.Tests.csproj
src/Universalis.Application/Universalis.Application.csproj
src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
src/Universalis.DataTransformations.Tests/Universalis.DataTransformations.Tests.csproj
src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
src/Universalis.DbAccess.Tests/Universalis.DbAccess.Tests.csproj
src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
src/Universalis.DbAccess/MarketBoard/ListingStore.cs
src/Universalis.DbAccess/Migrations/0010_AddListingUploadTime.cs
src/Universalis.DbAccess/Universalis.DbAccess.csproj
src/Universalis.Entities/MarketBoard/Listing.cs
src/Universalis.Entities/Universalis.Entities.csproj
src/Universalis.GameData.Tests/Universalis.GameData.Tests.csproj
src/Universalis.GameData/Universalis.GameData.csproj

Probably need to clean up the migration file and/or the implementation but this is what I was testing against locally.
The redis -> postgres doesn't use the algorithm since I didn't notice it until now.

ListingStore CTE and date based live tracking

---

src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
src/Universalis.DbAccess/MarketBoard/ListingStore.cs

* Perform ID fill in CurrentlyShownStore
* Fill if listing IDs are null or empty to handle possible edge cases
* Store UtcDateTime instead of DateTimeOffset for so Npgsql doesn't error

Listing ID fill adjustments

---

src/Universalis.DbAccess/MarketBoard/SaleStore.cs

Clean up how the caches are purged to try once per itemID/worldID

perf(SaleStore): batch inserts by the partition key itemID and worldID

---

src/Universalis.Application/Startup.cs
src/Universalis.Application/Universalis.Application.csproj
src/Universalis.DbAccess/MarketBoard/ListingStore.cs
src/Universalis.DbAccess/Universalis.DbAccess.csproj

OtlpEndpoint is configuration for URI or UNIVERSALIS_OLTP_ENDPOINT

perf: Add OpenTelemetry

---

src/Universalis.DbAccess.Tests/Uploads/DailyUploadCountStoreTests.cs
src/Universalis.DbAccess/Uploads/DailyUploadCountStore.cs
src/Universalis.DbAccess/Uploads/RecentlyUpdatedItemsStore.cs
src/Universalis.DbAccess/Uploads/WorldItemUploadStore.cs

Just merging some calls and adding FireAndForget to some things.

Minor round-trip time optimizations

---

src/Universalis.DbAccess/AccessControl/ApiKeyStore.cs
src/Universalis.DbAccess/CharacterStore.cs
src/Universalis.DbAccess/MarketBoard/SaleStore.cs
src/Universalis.DbAccess/Uploads/FlaggedUploaderStore.cs

Timeouts when connecting to Scylla can cause the application to crash here. I think I will Lazy<T> it.

Make Scylla not load in service ctors

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

Hopefully this allows Npgsql to make connection-related optimizations.

Don't batch single world/item queries

---

src/Universalis.DbAccess/MarketBoard/CurrentlyShownStore.cs
src/Universalis.DbAccess/MarketBoard/ListingStore.cs

This should be checked in a test (I thought it was).

Actually iterate correctly in ListingsStore

---

src/Universalis.DbAccess/MarketBoard/ListingStore.cs

I heard you like batches, so I batched your batches.
Multiplexes several `RetrieveManyLive` calls over a single batch command.

Go beyond, batch batches

---

src/Universalis.DbAccess/MarketBoard/ListingStore.cs

It might be doable, but not like this. This should be extracted to a new service.

Get rid of batch multiplexing

---

src/Universalis.Application.Tests/Controllers/V1/DeleteListingControllerTests.cs
src/Universalis.Application.Tests/Mocks/DbAccess/Uploads/MockUploadLogDbAccess.cs
src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
src/Universalis.Application/Controllers/V1/DeleteListingController.cs
src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs
src/Universalis.DbAccess/DbAccessExtensions.cs
src/Universalis.DbAccess/Migrations/0012_CreateUploadLog.cs
src/Universalis.DbAccess/Uploads/IUploadLogDbAccess.cs
src/Universalis.DbAccess/Uploads/IUploadLogStore.cs
src/Universalis.DbAccess/Uploads/UploadLogDbAccess.cs
src/Universalis.DbAccess/Uploads/UploadLogStore.cs
src/Universalis.Entities/Uploads/UploadLogEntry.cs

Just tracks market board uploads and listing deletions; this doesn't currently store all upload parameters.

Add basic upload log

---

src/Universalis.DbAccess/Uploads/UploadLogStore.cs

This was only on canary so yolo

Fix upload log SQL syntax

---

src/Universalis.Application/Common/WorldDcRegion.cs
src/Universalis.GameData/CsvGameDataProvider.cs
src/Universalis.GameData/KoreanServers.cs

Added korean server's world ids and names for kr server support

Add Korea Server World Ids

---

src/Universalis.GameData/LuminaGameDataProvider.cs

Add kr server world ids

---

src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs
src/Universalis.Application/Views/V1/CurrentlyShownView.cs

Add unitsSold, unitsForSale, listingsCount, and recentHistoryCount

---

src/Universalis.Application.Tests/Controllers/V1/HistoryControllerTests.cs
src/Universalis.Application.Tests/Controllers/V2/HistoryControllerTests.cs
src/Universalis.Application/Controllers/HistoryControllerBase.cs
src/Universalis.Application/Controllers/V1/HistoryController.cs
src/Universalis.Application/Controllers/V2/HistoryController.cs

Add min/max sale filters (#1162)

---

src/Universalis.Application/Controllers/HistoryControllerBase.cs
src/Universalis.Application/Controllers/V1/HistoryController.cs
src/Universalis.Application/Controllers/V2/HistoryController.cs

Set history entriesWithinSeconds default to 7 days
I will also add a documents update PR in this comment after.
closes: https://github.com/Universalis-FFXIV/Universalis/issues/1177

Set history entriesWithinSeconds default to 7 days

---

src/Universalis.Application/Controllers/HistoryControllerBase.cs

Changes the history endpoint to not use `IAsyncEnumerable<T>` to transform sales, since it doesn't do anything async and therefore hurts performance for no reason. See also: #582

Make sale result processing not use sync-over-async LINQ

---

src/Universalis.DbAccess/MarketBoard/HistoryDbAccess.cs

Self-explanatory, this just makes some database requests concurrent, which should improve performance unless the additional database load causes other problems.

Optimize HistoryDbAccess.RetrieveMany to do DB requests concurrently

---

src/Universalis.DbAccess/MarketBoard/CurrentlyShownDbAccess.cs
src/Universalis.DbAccess/MarketBoard/SaleStore.cs

* [Add spans for CurrentlyShownDbAccess](https://github.com/Universalis-FFXIV/Universalis/commit/cce0324eb5457e6604b306c7d1c987a53b238848)
* [Throttle RetrieveBySaleTime](https://github.com/Universalis-FFXIV/Universalis/commit/6af6a31ef82019148dc33192b4ff4ed7ec3532fd)

More improvements

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

This will narrow down whether performance issues are happening during an initial DB request or when iterating DB result pages.

Collect traces for DB collection iteration

---

src/Universalis.DbAccess.Tests/DbFixture.cs
src/Universalis.DbAccess.Tests/MarketBoard/ListingStoreTests.cs
src/Universalis.DbAccess/MarketBoard/ListingStore.cs

Hopefully this doesn't explode

Create listings cache

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

This reverts commit 62135eb8823ecefd6b20b6b1d1e8638b7cd4b312.

Revert "Restore sales (#1328)"

---

src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

This reverts commit 44e04ccb1eb2b910fa32696b62d9ba5bb5523e9c.

Revert "Revert "Restore sales (#1328)" (#1333)"

---

src/Universalis.Application.Tests/Controllers/V1/CurrentlyShownControllerTests.cs
src/Universalis.Application.Tests/Controllers/V2/CurrentlyShownControllerTests.cs
src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs

Process region and DC history when batching requests

---

src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs

Trivial mitigation which partially addresses #1346.

Publish listings/remove before listings/add

---

src/Universalis.DbAccess/MarketBoard/SaleStore.cs

This reverts commit 53b1f4f488c3a8db2c6b648805b06d35f65929e1.

Revert "Remove SaleStore semaphore (#1353)"

---

src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs
src/Universalis.Application/Controllers/V2/CurrentlyShownController.cs

This reverts commit 68efca94773d9d9558dd623b99220e660aee6d37.

Revert "Cap sales from the current data endpoint at 200 (#1363)"

---

src/Universalis.Application.Tests/Controllers/V2/HistoryControllerTests.cs
src/Universalis.Application/Controllers/HistoryControllerBase.cs
src/Universalis.Application/Controllers/V1/HistoryController.cs
src/Universalis.Application/Controllers/V2/HistoryController.cs
src/Universalis.Application/Controllers/V3/Market/SalesController.cs
src/Universalis.DbAccess.Tests/MarketBoard/HistoryDbAccessTests.cs
src/Universalis.DbAccess.Tests/MarketBoard/SaleStoreTests.cs
src/Universalis.DbAccess.Tests/SeedDataGenerator.cs
src/Universalis.DbAccess/MarketBoard/HistoryDbAccess.cs
src/Universalis.DbAccess/MarketBoard/ISaleStore.cs
src/Universalis.DbAccess/MarketBoard/SaleStore.cs
src/Universalis.DbAccess/Queries/MarketBoard/HistoryManyQuery.cs

Add entriesUntil parameter to V1/V2 history API (#1369)

---

.github/workflows/codeql-analysis.yml
.nuke/build.schema.json
Dockerfile
build/Build.cs
build/_build.csproj
src/Universalis.Alerts.Tests/Universalis.Alerts.Tests.csproj
src/Universalis.Alerts/Universalis.Alerts.csproj
src/Universalis.Application.Tests/Universalis.Application.Tests.csproj
src/Universalis.Application/Universalis.Application.csproj
src/Universalis.Common/Universalis.Common.csproj
src/Universalis.DataTransformations.Tests/Universalis.DataTransformations.Tests.csproj
src/Universalis.DataTransformations/Universalis.DataTransformations.fsproj
src/Universalis.DbAccess.Tests/Universalis.DbAccess.Tests.csproj
src/Universalis.DbAccess/Universalis.DbAccess.csproj
src/Universalis.Entities/Universalis.Entities.csproj
src/Universalis.GameData.Tests/Universalis.GameData.Tests.csproj
src/Universalis.GameData/CsvGameDataProvider.cs
src/Universalis.GameData/LuminaGameDataProvider.cs
src/Universalis.GameData/Regions.cs
src/Universalis.GameData/Universalis.GameData.csproj
src/Universalis.Mogboard.Tests/Universalis.Mogboard.Tests.csproj
src/Universalis.Mogboard/Universalis.Mogboard.csproj
src/Universalis.Tests/Universalis.Tests.csproj
src/Universalis.sln

- Newer
- Faster
- Actually supported by dependencies

Upgrade to .NET 8

---

src/Universalis.Application.Tests/Uploads/Behaviors/MarketBoardUploadBehaviorTests.cs
src/Universalis.Application/Uploads/Behaviors/MarketBoardUploadBehavior.cs

It doesn't exist in the network data anymore.

Fill in lastReviewTime as the current time if it's not provided
